version: '3'
services:
  web:
    build: .
    ports:
        -   '8080:8080'
    environment: 
        -   MONGO_DBCONNECTION=mongodb://mongodb:27017/todos
    depends_on: 
        - mongodb
    links: 
        -   mongodb
  mongodb:
    image: mongo:latest
    volumes: 
        -   ~/mongo-volume:/data/db
    ports: 
        -   '27017-27019:27017-27019'
