apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-todo-app
  template:
    metadata:
      labels:
        app: nodejs-todo-app
    spec:
      containers:
      - name: nodejs-todo
        image: gcr.io/dansand/github.com/svdansand/nodejs-todo:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DBCONNECTION
          value: "mongodb://mongo:27017/todo"
        - name: MONGO_DBCONNECTION2
          value: "mongodb://mongo:27017/todo"