apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-todo-app
  template:
    metadata:
      labels:
        app: nodejs-todo-app
    spec:
      containers:
      - name: nodejs-todo
        image: gcr.io/dansand/github.com/svdansand/nodejs-todo
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m" 
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DBCONNECTION
          value: "mongodb://mongo:27017/todo"
---
apiVersion: v1
kind: Service
metadata:
 name: nodejs-todo
 labels:
   name: nodejs-todo
spec:
 ports:
 - port: 8080
   targetPort: 80
 type: LoadBalancer
 selector:
   app: nodejs-todo-app